# Generated by Django 2.2.7 on 2019-12-15 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20191126_1518'),
    ]

    operations = [
        migrations.CreateModel(
            name='Library',
            fields=[

            ],
        ),
    ]
