# Generated by Django 2.2.7 on 2019-12-20 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_library'),
    ]

    operations = [
        migrations.AddField(
            model_name='library',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='library',
            name='name',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='library',
            name='owner',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
