# Generated by Django 2.2.7 on 2019-12-20 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20191220_1448'),
    ]

    operations = [
        migrations.RenameField(
            model_name='library',
            old_name='description',
            new_name='dateFoundation',
        ),
        migrations.AddField(
            model_name='library',
            name='location',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
